# https://eslint.org/docs/user-guide/configuring
---
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
  ecmaFeatures:
    experimentalObjectSpread: true
    jsx: true

plugins:
  - "react"
  - "jest"

extends:
  - "plugin:react/recommended"
  - "plugin:jest/recommended"

env:
  es6: true
  node: true
  jest: true
  jest/globals: true

globals:
  mount: true
  shallow: true
  render: true
  document: true
  fetch: true
  window: true

rules:
  react/prop-types: "warn"
  prefer-promise-reject-errors: "off"
  no-invalid-this: "off"
  babel/no-invalid-this: "off"

settings:
  react:
    version: "16.4"